on:
  push:
    branches:
      - master

jobs:
  # JOB to run change detection
  changes:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    outputs:
      jobs: ${{ steps.filter.outputs.nomadjobs_files }}
      volumes: ${{ steps.filter_volumes.outputs.volumes_files }}
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4

    - uses: dorny/paths-filter@v3
      id: filter_volumes
      with:
        list-files: 'json'
        filters: |
          volumes: 
            - '**/volume.hcl'
            - 'plex/plex-database-volume.hcl'

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        list-files: 'json'
        filters: |
          nomadjobs: 
            - 'plex/*.job'
            - 'sonarr/*.job'
            - 'radarr/*.job'
            - 'lidarr/*.job'
            - 'postgres/*.job'
            - 'paperless/*.job'
            - 'mariadb/*.job'
            - 'coredns/*.job'
            - 'docker-registry/*.job'
            - 'github-runner/*.job'
            - 'iscsi-csi-plugin/*.job'
            - 'keepalived/*.job'
            - 'pihole/*.job'
            - 'sabnzbd/*.job'
            - 'sickchill/*.job'
            - 'smtp/*.job'
            - 'www/*.job'
            - 'ollama/*.job'
            - 'open-webui/*.job'
            - 'paperless-ai/*.job'

  add_volumes:
    runs-on: self-hosted
    needs: changes
    if: needs.changes.outputs.volumes != '[]'
    continue-on-error: true
    strategy:
      matrix:
        job: ${{ fromJSON(needs.changes.outputs.volumes ) }}

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4

    - uses: lucasmelin/setup-nomad@v2

    - name: deploy
      shell: bash
      run: |
        nomad volume create ${{ matrix.job }}
      env:
        NOMAD_ADDR: 'http://nomad.service.home:4646'

  deploy_jobs:
    runs-on: self-hosted
    needs: changes
    if: needs.changes.outputs.jobs != '[]'
    continue-on-error: true
    strategy:
      matrix:
        job: ${{ fromJSON(needs.changes.outputs.jobs ) }}

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4

    - uses: lucasmelin/setup-nomad@v2

    - name: deploy
      shell: bash
      run: |
        nomad job run ${{ matrix.job }}
      env:
        NOMAD_ADDR: 'http://nomad.service.home:4646'
        NOMAD_VAR_region: 'home'
        NOMAD_VAR_tld: '${{ secrets.NOMAD_VAR_tld }}' # Corrected case
        NOMAD_VAR_shared_dir: '/home/shared/'
        NOMAD_VAR_downloads_dir: '/home/sabnzbd/downloads'
        NOMAD_VAR_music_dir: '/home/media/Music'
        NOMAD_VAR_movies_dir: '/home/media/Movies'
        NOMAD_VAR_books_dir: '/home/media/Books'
        NOMAD_VAR_tv_dir: '/home/media/TV'
        NOMAD_VAR_media_dir: '/home/media'
        # NOMAD_VAR_auth: '${{ secrets.NOMAD_VAR_AUTH }}' # Removed
        # NOMAD_VAR_otr_pass: '${{ secrets.NOMAD_VAR_OTR_PASS }}' # Removed
        # NOMAD_VAR_web_pass: '${{ secrets.NOMAD_VAR_WEB_PASS }}' # Removed
        NOMAD_VAR_hass_key: '${{ secrets.NOMAD_VAR_hass_key }}' # Corrected case
        NOMAD_VAR_github_pat: ${{ secrets.NOMAD_VAR_github_pat }} # Corrected case
        NOMAD_VAR_datacenters_all: '["dc1", "public"]'
        NOMAD_VAR_datacenters_dc1: '["dc1"]'
        NOMAD_VAR_datacenters_public: '["public"]'
        NOMAD_VAR_tailscale_auth: '${{ secrets.NOMAD_VAR_tailscale_auth }}' # Corrected case
        NOMAD_VAR_tailscale_auth_este: '${{ secrets.NOMAD_VAR_tailscale_auth_este }}' # Corrected case
        NOMAD_VAR_oauth_client_id: '${{ secrets.NOMAD_VAR_oauth_client_id }}' # Corrected case
        NOMAD_VAR_oauth_client_secret: '${{ secrets.NOMAD_VAR_oauth_client_secret }}' # Corrected case
        NOMAD_VAR_oauth_secret: '${{ secrets.NOMAD_VAR_oauth_secret }}' # Corrected case
        NOMAD_VAR_oauth_emails: '${{ secrets.NOMAD_VAR_oauth_emails }}' # Corrected case
        # NOMAD_VAR_pushover_token: '${{ secrets.NOMAD_VAR_PUSHOVER_TOKEN }}' # Removed
        NOMAD_VAR_pushover_user_key: '${{ secrets.NOMAD_VAR_pushover_user_key }}' # Corrected case
        NOMAD_VAR_ssh_id: '${{ secrets.NOMAD_VAR_ssh_id }}' # Corrected case
        NOMAD_VAR_truenas_api_key: '${{ secrets.NOMAD_VAR_truenas_api_key }}' # Corrected case
        NOMAD_VAR_gh_access_token: '${{ secrets.NOMAD_VAR_gh_access_token }}' # Corrected case
        # NOMAD_VAR_postgres_admin_password: '${{ secrets.NOMAD_VAR_POSTGRES_ADMIN_PASSWORD }}' # Removed
        # NOMAD_VAR_paperless_admin_password: '${{ secrets.NOMAD_VAR_PAPERLESS_ADMIN_PASSWORD }}' # Removed
        # NOMAD_VAR_db_password: '${{ secrets.NOMAD_VAR_DB_PASSWORD }}' # Removed
        NOMAD_VAR_ollama_data_dir: '/home/shared/ollama'
        NOMAD_VAR_ollama_base_url: 'http://ollama.service.consul:11434'
        NOMAD_VAR_webui_secret_key: '${{ secrets.NOMAD_VAR_webui_secret_key }}' # Corrected case
        NOMAD_VAR_datacenter: 'dc1'
        NOMAD_VAR_dns_server_ip: '192.168.50.2'
        # Added missing variables
        NOMAD_VAR_aws_access_key: ${{ secrets.NOMAD_VAR_aws_access_key }}
        NOMAD_VAR_aws_secret_key: ${{ secrets.NOMAD_VAR_aws_secret_key }}
        NOMAD_VAR_bedrock_aws_region: ${{ secrets.NOMAD_VAR_bedrock_aws_region }}
        NOMAD_VAR_gcp_dns_admin: ${{ secrets.NOMAD_VAR_gcp_dns_admin }}
        NOMAD_VAR_gemini_api_key: ${{ secrets.NOMAD_VAR_gemini_api_key }}
        NOMAD_VAR_litellm_master_key: ${{ secrets.NOMAD_VAR_litellm_master_key }}
        NOMAD_VAR_manyfold_secret_key: ${{ secrets.NOMAD_VAR_manyfold_secret_key }}
        NOMAD_VAR_postgres_pass: ${{ secrets.NOMAD_VAR_postgres_pass }}
        NOMAD_VAR_truenas_iscsi_pass: ${{ secrets.NOMAD_VAR_truenas_iscsi_pass }}
